### ISSUE TITLE
TODO / Ideas List

### ISSUE THREAD

**Issue by Minizbot2012** [valarnin/ACTAssemblyLoader#1]
- [ ] Change preload textbox into a list box
   - [ ] Add controls to add / remove from preload list
- [ ] Better error handling when failure to load dll occurs
- [ ] instead of logging to status text add a readonly logging textbox?
- [ ] List not complete
I'm up late tonight so I'll be working on this

**Comment by valarnin** [comment]
re: Logging. Might make sense to make the GUI control a tab pane, put settings on tab 1 and log on tab 2? Could also do the same with the TTS plugin.

**Comment by Minizbot2012** [comment]
I ended up doing a listbox kinda like how overlay plugin handles it; I'll sleep on it tonight for now; I just pushed the rework into my personal github (figured do it by pr after we agree)
